---

- name: print to variable
  hosts: web
  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "i am lerning aws with devops duration 120+ hours and trainer is siva kumar reddy"