- name: print to variable
  hosts: web
  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "i am lerning course: {{COURSE}} duration is {{DURATION}} and trainer is {{TRAINER}}"