- name: data types in ansible
  hosts: web
  vars:
    course: DevOps with AWS
    duration: 120+ hours
    trainer: Pavan Reddy
    topics:
    - linux
    - shell
    - ansible
    - terrafrom
    - aws
    - k8
    live: true
    tools:
      ci: jenkins
      cm: ansible
      cloud: aws
    aws:
    - ec2
    - s3
  tasks:
    - name: devops with aws course information
      ansible.builtin.debug:
        msg: "i am lerning course {{course}} duraion is {{duration}} and trainer {{trainer}} and it's going to live {{live}} topics will cover {{topics}} and tools are {{tools}} and aws services {{aws}}"