---
- name: data-types concepts
  hosts: web
  vars:
    corse: devops with aws #string
    duration: 120+ #number
    trainer: pavan reddy #string
    topics:
    - linux
    - shell
    - ansible
    - terraform
    - aws
    - k8
    live: true
    tools:
      ci: jenkins
      cm: ansible
      cloud: aws
    aws:
    - s3
    - ec2
  tasks:
    - name: devops course information
      ansible.builtin.debug:
        msg: "i am lerning course: {{corse}} duration is {{duration}} hours and trainer is {{trainer}}  topics are: {{topics}} live : {{live}} tools are : {{tools}} aws services is {{aws}}"