- name: data types in ansible
  hosts: web
  tasks:
    - name: devops wioth aws course information
      ansible.builtin.debug:
        msg: "i am lerning course {{course}} duraion is {{duraion}} and trainer {{trainer}} and it's going to live {{live}} topics will cover {{topics}} and tools are {{tools}} and aws services {{aws}}"