- name:  check a number is less than 10 or not
  hosts: web
  vars_prompt:
  - name: my_number
    prompt: please enter the number
    private: false
  tasks:
    - name: print this if less than 10
      ansible.builtin.debug:
        msg: given number {{my_number}} less than 10
      when: my_number | < 10

    - name: print this if greater than 10
      ansible.builtin.debug:
        msg: given number {{my_number}}  greater than 10
      when: my_number | > 10