- name: demo on filters/functions
  hosts: web
  # connection: local
  tasks:
    - name: print the default variable
      ansible.builtin.debug:
        msg: "Hello {{ course | default('Pavan')}}"

    - name: convert to uppercase
      vars: 
        name: "hello pavan"
      ansible.builtin.debug:
        msg: "{{ name | upper }}"

