- name: demo on filters/functions
  hosts: web
  # connection: local
  tasks:
    - name: print the default variable
      ansible.builtin.debug:
        msg: "Hello {{ course | default('Pavan')}}"

    - name: convert to upper
      vars: 
        name: hello reddy
      ansible.builtin.debug:
        msg: "{{ name | upper}}"

    - name: convert to lower
      vars: 
        name: HELLO REDDY
      ansible.builtin.debug:
        msg: "{{ name | lower}}"

    - name: get the unique values
      vars: 
        name: [1,2,3,45,3,2,4]
      ansible.builtin.debug:
        msg: "{{ name | unique }}"

    - name: get the min and max
      vars: 
        numbers: [1,2,3,45,3,2,4]
      ansible.builtin.debug:
        msg: "min: {{ numbers | min }}, max: {{ numbers | max }}"

    - name: convert map to list
      vars:
      course: 
        name: "devops with aws"
        duration: "120"
        trainer: "pavan reddy"
      ansible.builtin.debug:
        msg: "{{ course | dict2items }}"

