- name: demo on filters/functions
  hosts: web
  tasks:
    - name: print the default variable
      ansible.builtin.debug:
        msg: "Hello {{ course | default('Pavan')}}"

    - name: convert to uppercase
      ansible.builtin.debug:
      vars: 
        greeting: pavan
        msg: "{{ greeting | upper }}"

