- name: demo on filters/functions
  hosts: web
  # connection: local
  tasks:
    - name: print the default variable
      ansible.builtin.debug:
        msg: "Hello {{ course | default('Pavan')}}"

    - name: conver to upper
      vars: 
        name: hello reddy
      ansible.builtin.debug:
        msg: "{{ name | upper}}"

    - name: conver to lower
      vars: 
        name: HELLO REDDY
      ansible.builtin.debug:
        msg: "{{ name | lower}}"

