- name: create-ec2-r53 recors
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-0426331dbce2e2bcb"
    sg_id: "sg-0e959ca03aa4adbf1"
    ami_id: "ami-09c813fb71547fc4f"
  instances:
  - mysql
  - backend
  - frontend
  tasks:
    - name: 
      amazon.aws.ec2_instance:
        name: 
        vpc_subnet_id: "{{subnet_id}}"
        instance_type: "t3.micro"
        security_group: "{{sg_id}}"
        image_id: "{{ami_id}}"
      loop: "{{instances}}"
      register: ec2_instances